-- MySQL Script generated by MySQL Workbench
-- Sat May 27 14:30:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Database` DEFAULT CHARACTER SET utf8 ;
USE `Database` ;

-- -----------------------------------------------------
-- Table `Database`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Database`.`PERSONA` (
  `per_id` INT NOT NULL,
  `per_nombre` VARCHAR(45) NULL,
  `per_apellido` VARCHAR(45) NULL,
  `per_rut` VARCHAR(10) NULL,
  PRIMARY KEY (`per_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Database`.`DIRECCION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Database`.`DIRECCION` (
  `dir_id` INT NOT NULL,
  `dir_calle` VARCHAR(45) NULL,
  `dir_numero` VARCHAR(45) NULL,
  `dir_comuna` VARCHAR(45) NULL,
  `PERSONA_per_id` INT NOT NULL,
  PRIMARY KEY (`dir_id`, `PERSONA_per_id`),
  INDEX `fk_DIRECCION_PERSONA_idx` (`PERSONA_per_id` ASC),
  CONSTRAINT `fk_DIRECCION_PERSONA`
    FOREIGN KEY (`PERSONA_per_id`)
    REFERENCES `Database`.`PERSONA` (`per_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
